
version: '2.1'

services:
  client:
    ports: ["3000:3000"]
    volumes: ["./client:/app"]
    build:
      context: client
      dockerfile: Dockerfile
  server:
    ports: ["10010:10010"]
    volumes: ["./server/app:/app"]
    build:
      context: server
      dockerfile: Dockerfile
